- hosts: clients

  tasks:
    - name: Sync docker image
      synchronize:
        src: "{{ src_dir }}/herbert_client_latest.tar.gz"
        dest: "{{ deploy_dir }}"

    - name: Load docker image
      ansible.builtin.shell:
        cmd: docker load < herbert_client_latest.tar.gz
        chdir: "{{ deploy_dir }}"

    - name: Stop running conatiner
      ansible.builtin.shell:
        cmd: docker container remove --force client-1

    - name: Run docker image as container
      ansible.builtin.shell:
        cmd: >
          docker run -d
          -p {{ client_port }}:{{ client_port }}
          -e "API_URL=http://api-1:{{ api_port }}"
          -e "WSS_PORT={{ wss_port }}"
          --network=herbert-net
          --name=client-1
          herbert_client:latest
