- hosts: clients

  vars:
    service_description: "Web Client for the Herbert system"
    container_name: "client-1"

  tasks:
    - name: Sync docker image
      synchronize:
        src: "{{ src_dir }}/herbert_client_latest.tar.gz"
        dest: "{{ deploy_dir }}"

    - name: Load docker image
      ansible.builtin.shell:
        cmd: docker load < herbert_client_latest.tar.gz
        chdir: "{{ deploy_dir }}"

    - name: Stop running conatiner
      ansible.builtin.shell:
        cmd: docker container remove --force {{ container_name }}

    - name: Run docker image as container
      ansible.builtin.shell:
        cmd: >
          docker run -d
          -p {{ client_port }}:{{ client_port }}
          --network=herbert-net
          --name={{ container_name }}
          herbert_client:latest

    - name: Install client service
      become: yes
      template:
        src: ./templates/systemd-service.j2
        dest: /etc/systemd/system/herbert-client.service
        owner: root
        group: root
        mode: "0644"

    - name: Enable and start herbert-client service
      become: yes
      systemd:
        name: herbert-client
        state: restarted
        daemon_reload: yes
        enabled: yes
