- hosts: controllers

  tasks:
    - name: Sync docker image
      synchronize:
        src: "{{ src_dir }}/herbert_controller_latest.tar.gz"
        dest: "{{ deploy_dir }}"

    - name: Load docker image
      ansible.builtin.shell:
        cmd: docker load < herbert_controller_latest.tar.gz
        chdir: "{{ deploy_dir }}"

    - name: Stop running conatiner
      ansible.builtin.shell:
        cmd: docker container remove --force controller-1

    - name: Run docker image as container
      ansible.builtin.shell:
        cmd: >
          docker run -d
          -e API_URL=http://api-1:{{ api_port }}
          -e WSS_URL=ws://socket-1:{{ wss_port }}
          --network=herbert-net
          --name=controller-1
          herbert_controller:latest
