# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: app-prettier
        name: Run prettier
        language: system
        files: ^.*$
        types_or: [javascript, json]
        entry: |
          bash -c 'npm run format "${@}"' --
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint
        name: Run eslint
        files: \.(vue|js|ts|tsx)?$
        additional_dependencies:
          - globals@13.21.0
          - eslint@9.17.0
          - eslint/js
          - eslint-config-prettier@9.1.0
          - eslint-plugin-vue@9.32.0
