- hosts: clients
  become: yes

  vars:
    - buildDir: "/etc/opt"
    - appDir: "{{ buildDir }}/herbert"
    - nodejs_version: "14.x"
    - nodejs_package_json_path: "{{appDir}}"
    - service_description: "Herbert client dashboard service"
    - service_user: "{{ansible_user}}"
    - service_file: index.js

  tasks:
    - name: Git Clone Repo
      become: no
      when: herbert_version != "local"
      git:
        repo: https://github.com/metatooth/herbert.git
        dest: "{{appDir}}"
        version: "{{herbert_version}}"
        force: yes

    - name: Sync local herbert repo
      become: no
      when: herbert_version == "local"
      synchronize:
        src: ../../../herbert
        dest: "{{buildDir}}"

    - name: Install nodejs {{nodejs_version}} and node_modules
      include_role:
        name: geerlingguy.nodejs

    - name: Build client
      become: no
      command: "chdir={{appDir}} npm run build:client"
      environment:
        VUE_APP_WS_URL: "ws://{{api_host}}:{{api_port}}"
        VUE_APP_API_URL: "http://{{api_host}}:{{api_port}}"

    - name: Install client service
      template:
        src: ./templates/systemd-service.j2
        dest: /etc/systemd/system/herbert-client.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start herbert-client service
      systemd:
        name: herbert-client
        state: restarted
        daemon_reload: yes
        enabled: yes
