- hosts: socket_servers

  tasks:
    - name: Create {{ app_dir }} on host
      file: "{{ app_dir }}"
      state: directory

    - name: Sync herbert dist
      synchronize:
        src: "{{ dist_dir }}/dist.tar.gz"
        dest: "{{ app_dir }}/dist.tar.gz"
        recursive: true
        delete: true

    - name: Sync herbert shared
      synchronize:
        src: "{{ distDir }}/shared"
        dest: "{{ appDir }}/dist"
        recursive: yes
        delete: yes

    - name: Sync herbert config
      synchronize:
        src: "{{ srcDir }}/config"
        dest: "{{ appDir }}"
        recursive: yes
        delete: yes

    - name: Sync herbert package.json
      synchronize:
        src: "{{ srcDir }}/package.json"
        dest: "{{ appDir }}"

    - name: Sync herbert package-lock.json
      synchronize:
        src: "{{ srcDir }}/package-lock.json"
        dest: "{{ appDir }}"

    - name: Install nodejs {{nodejs_version}}
      include_role:
        name: geerlingguy.nodejs
        apply:
          become: yes

    - name: Install production node_modules
      command: npm install
      args:
        chdir: "{{ appDir }}"
      environment:
        NODE_ENV: production

    - name: Install socket-server service
      become: yes
      template:
        src: ./templates/systemd-service.j2
        dest: /etc/systemd/system/herbert-socket-server.service
        owner: root
        group: root
        mode: "0644"

    - name: Enable and start herbert-socket-server service
      become: yes
      systemd:
        name: herbert-socket-server
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: Create .bash_aliases
      copy:
        dest: /home/{{ ansible_user }}/.bash_aliases
        content: |
          alias tail-socket-server='sudo journalctl -u herbert-socket-server -f'
