- hosts: workers
  become: yes

  vars:
    - buildDir: "/etc/opt"
    - appDir: "{{buildDir}}/herbert"
    - nodejs_version: "14.x"
    - nodejs_package_json_path: "{{appDir}}"
    - service_description: "Herbert in-room worker service"
    - service_user: root
    - service_file: dist/worker/main.js
    - node_env: "{{config_name}}"

  tasks:
    - name: Install System Dependencies
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - bluetooth
        - bluez
        - libbluetooth-dev
        - libudev-dev
        - git
        - gcc
        - g++
        - make

    - name: Git Clone Repo
      become: no
      when: herbert_version != "local"
      git:
        repo: https://github.com/metatooth/herbert.git
        dest: "{{appDir}}"
        version: "{{herbert_version}}"
        force: yes

    - name: Sync local herbert repo
      become: no
      when: herbert_version == "local"
      synchronize:
        src: ../../../herbert
        dest: "{{buildDir}}"

    - name: Install nodejs {{nodejs_version}} and node_modules
      when: herbert_version != "local"
      include_role:
        name: geerlingguy.nodejs

    - name: Build worker
      become: no
      when: herbert_version != "local"
      command: "chdir={{appDir}} npm run build:worker"

    - name: Install worker service
      template:
        src: ./templates/systemd-service.j2
        dest: /etc/systemd/system/herbert-worker.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start herbert-worker service
      systemd:
        name: herbert-worker
        state: restarted
        daemon_reload: yes
        enabled: yes
